version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: ${NODE_ENV}
        GOOGLE_GENERATIVE_AI_API_KEY: ${GOOGLE_GENERATIVE_AI_API_KEY}
        ARCJET_KEY: ${ARCJET_KEY}
        NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL}
        COORDINATE_EXTRACTION_API_URL: ${COORDINATE_EXTRACTION_API_URL}
    ports:
      - "7400:3000"
