export { default as LandingPage } from './LandingPage'
export { default as Header } from './Header'
export { default as HomeSection } from './HomeSection'
export { default as AboutSection } from './AboutSection'
export { default as ServicesSection } from './ServicesSection'
export { default as ContactSection } from './ContactSection'
export { default as Footer } from './Footer'
export { default as ScrollUp } from './ScrollUp'