name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Create .env file
        run: |
          echo "NODE_ENV=production" > .env
          echo "GOOGLE_GENERATIVE_AI_API_KEY=${{ secrets.GOOGLE_GENERATIVE_AI_API_KEY }}" >> .env
          echo "ARCJET_KEY=${{ secrets.ARCJET_KEY }}" >> .env
          echo "NEXT_PUBLIC_APP_URL=${{ secrets.NEXT_PUBLIC_APP_URL }}" >> .env
          echo "COORDINATE_EXTRACTION_API_URL=${{ secrets.COORDINATE_EXTRACTION_API_URL }}" >> .env


      - name: Build and run containers
        run: docker compose --env-file .env up -d --build

